<a href="https://colab.research.google.com/github/shravan1808/DeepLearningProjects/blob/main/Project_01/Project_01_DL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
X_data = np.array([
    [0.45, 12, 1, 2], [0.89, 35, 4, 3], [0.25, 2, 0, 1], [0.98, 85, 8, 4], [0.78, 28, 3, 3],
    [0.35, 8, 1, 2],  [0.20, 3, 0, 1],  [0.95, 38, 5, 3], [0.99, 92, 9, 4], [0.40, 10, 1, 2],
    [0.22, 2, 0, 1],  [0.85, 31, 3, 3], [0.42, 11, 1, 2], [0.92, 78, 7, 4], [0.28, 3, 0, 1],
    [0.92, 36, 4, 3], [0.38, 7, 1, 2],  [0.99, 88, 8, 4], [0.21, 2, 0, 1],  [0.88, 33, 3, 3],
    [0.41, 9, 1, 2],  [0.24, 3, 0, 1],  [0.96, 40, 4, 3], [0.97, 75, 7, 4], [0.39, 8, 1, 2],
    [0.18, 1, 0, 1],  [0.90, 34, 3, 3], [0.99, 90, 9, 4], [0.26, 4, 0, 1],  [0.84, 32, 3, 3],
    [0.43, 10, 1, 2], [0.37, 8, 1, 2],  [0.98, 81, 8, 4], [0.19, 1, 0, 1],  [0.99, 42, 5, 3],
    [0.44, 9, 1, 2],  [0.99, 89, 8, 4], [0.23, 3, 0, 1],  [0.91, 35, 4, 3], [0.36, 11, 1, 2],
    [0.27, 2, 0, 1],  [0.93, 37, 4, 3], [0.96, 80, 7, 4], [0.40, 12, 1, 2], [0.18, 1, 0, 1],
    [0.94, 38, 4, 3], [0.99, 86, 8, 4], [0.33, 7, 1, 2],  [0.87, 31, 3, 3], [0.38, 9, 1, 2]
])

In [ ]:
X_mean = X_data.mean(axis=0)
X_std = X_data.std(axis=0)

X_data = (X_data - X_mean) / (X_std + 1e-8)

In [ ]:
y_data = np.array([
    [0], [1], [0], [1], [1], [0], [0], [1], [1], [0],
    [0], [1], [0], [1], [0], [1], [0], [1], [0], [1],
    [0], [0], [1], [1], [0], [0], [1], [1], [0], [1],
    [0], [0], [1], [0], [1], [0], [1], [0], [1], [0],
    [0], [1], [1], [0], [0], [1], [1], [0], [1], [0]
])

In [ ]:
#TASK 1
def relu(z):
  return np.maximum(0,z)

def relu_derivative(z):
  return np.where(z>0,1,0)

def sigmoid(z):
  return 1/(1+np.exp(-z))

def sigmoid_derivative(z):
  return sigmoid(z)*(1-sigmoid(z))

In [ ]:
#TASK 2
np.random.seed(42)
w1 = 0.01 * np.random.randn(4,8)
w2 = 0.01 * np.random.randn(8,1)
b1 = np.zeros((1,8))
b2 = np.zeros((1,1))


In [ ]:
#TASK 3
Z1 = X_data @ w1 + b1
A1 = relu(Z1)
Z2 = A1 @ w2 + b2
A2 = sigmoid(Z2)

In [ ]:
print("Z1:", Z1.shape)
print("A1:", A1.shape)
print("Z2:", Z2.shape)
print("A2:", A2.shape)

print(A2[:5])

Z1: (50, 8)
A1: (50, 8)
Z2: (50, 1)
A2: (50, 1)
[[0.49992477]
 [0.49994678]
 [0.49989614]
 [0.49996931]
 [0.49995579]]


In [ ]:
#TASK 4
def binary_cross_entropy(y_true,y_pred):
  epsilon = 1e-15
  y_pred = np.clip(y_pred,epsilon,1-epsilon)
  avg_loss = -np.mean(y_true*np.log(y_pred)+(1-y_true)*np.log(1-y_pred))
  return avg_loss

In [ ]:
loss = binary_cross_entropy(y_data,A2)
print(loss)

0.6931004346144094


In [ ]:
#TASK 5
N = X_data.shape[0]
# dZ2 = A2 - y, dW2 = A1^T * dZ2 / N, dA1 = dZ2 * W2^T, dZ1 = dA1 * ReLU'(Z1), dW1 = X^T * dZ1 / N
dZ2 = A2 - y_data
dW2 = A1.T @ dZ2 / N
db2 = np.sum(dZ2, axis=0, keepdims=True) / N
dA1 = dZ2 @ w2.T
dZ1 = dA1 * relu_derivative(Z1)
dW1 = X_data.T @ dZ1 / N
db1 = np.sum(dZ1, axis=0, keepdims=True) / N

In [ ]:
print(dW1.shape)
print(dW2.shape)
print(db1.shape)
print(db2.shape)

(4, 8)
(8, 1)
(1, 8)
(1, 1)


In [ ]:
print(w1)

[[ 0.00496714 -0.00138264  0.00647689  0.0152303  -0.00234153 -0.00234137
   0.01579213  0.00767435]
 [-0.00469474  0.0054256  -0.00463418 -0.0046573   0.00241962 -0.0191328
  -0.01724918 -0.00562288]
 [-0.01012831  0.00314247 -0.00908024 -0.01412304  0.01465649 -0.00225776
   0.00067528 -0.01424748]
 [-0.00544383  0.00110923 -0.01150994  0.00375698 -0.00600639 -0.00291694
  -0.00601707  0.01852278]]


In [ ]:
#TASK 6
alpha = 0.1
w1 = w1 - alpha * dW1
w2 = w2 - alpha * dW2
b1 = b1 - alpha * db1
b2 = b2 - alpha * db2

In [ ]:
print(w1)

[[ 0.00496332 -0.00161703  0.00667635  0.01500567 -0.00230042 -0.00281659
   0.01530051  0.00772718]
 [-0.00469756  0.00520954 -0.00446606 -0.0047594   0.00246163 -0.01953333
  -0.01755239 -0.00558   ]
 [-0.01013118  0.00292014 -0.00890653 -0.01424273  0.01470018 -0.00267161
   0.0003427  -0.01420387]
 [-0.00544716  0.00089235 -0.01132831  0.00362124 -0.00596687 -0.00334966
  -0.00640847  0.018567  ]]


In [ ]:
#TASK 7
N = X_data.shape[0]
alpha = 0.1
loss_history =[]
for epoch in range(100):
  Z1 = X_data @ w1 + b1
  A1 = relu(Z1)
  Z2 = A1 @ w2 + b2
  A2 = sigmoid(Z2)
  loss = binary_cross_entropy(y_data,A2)
  loss_history.append(loss)
  dZ2 = A2 - y_data
  dW2 = A1.T @ dZ2 / N
  db2 = np.sum(dZ2, axis=0, keepdims=True) / N
  dA1 = dZ2 @ w2.T
  dZ1 = dA1 * relu_derivative(Z1)
  dW1 = X_data.T @ dZ1 / N
  db1 = np.sum(dZ1, axis=0, keepdims=True) / N
  w1 = w1 - alpha * dW1
  w2 = w2 - alpha * dW2
  b1 = b1 - alpha * db1
  b2 = b2 - alpha * db2


In [ ]:
print("First:", loss_history[:5])
print("Last:", loss_history[-5:])
print("Final loss:", loss_history[-1])

First: [np.float64(0.6930327549312365), np.float64(0.6929664058051647), np.float64(0.6929009756762575), np.float64(0.6928364517625732), np.float64(0.6927719076064734)]
Last: [np.float64(0.3259162768145309), np.float64(0.31634607597355374), np.float64(0.30690366779617967), np.float64(0.29759914214275585), np.float64(0.28844290934003036)]
Final loss: 0.28844290934003036


In [ ]:
y_pred = np.where(A2 >= 0.5, 1, 0)


In [ ]:
print(y_pred.shape)
print(y_pred[:10])

(50, 1)
[[0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]]


In [ ]:
print(np.unique(y_pred, return_counts=True))

(array([0, 1]), array([26, 24]))


In [ ]:
accuracy = np.mean(y_pred == y_data)
print("Accuracy:", accuracy*100)

Accuracy: 100.0


In [ ]:
new_cust = [0.95, 80, 7, 4]
new_cust = (new_cust - X_mean) / (X_std + 1e-8)
new_cust = np.array([new_cust])

In [ ]:
z1_new = new_cust @ w1 + b1
a1_new = relu(z1_new)
z2_new = a1_new @ w2 + b2
a2_new = sigmoid(z2_new)
print(a2_new)
y_pred_new = np.where(a2_new >= 0.5, 1, 0)
print(y_pred_new)

[[0.69846765]]
[[1]]


In [ ]:
print("\n========== WEEK 5 DAY 21: NEURAL NETWORK ENGINE FROM SCRATCH ==========")

print("\nArchitecture Parameters:")
print(f"- Input Features           : {X_data.shape[1]}")
print(f"- Hidden Layer Neurons     : {w1.shape[1]} (Activation: ReLU)")
print(f"- Output Neurons           : {w2.shape[1]} (Activation: Sigmoid)")
print(f"- Dataset Records          : {X_data.shape[0]} Samples")


print("\nTraining Initialization:")
print("- Loss Function            : Binary Cross-Entropy (BCE)")
print("- Optimizer                : Vanilla Gradient Descent (SGD)")
print(f"- Initial Loss (Epoch 1)   : {loss_history[0]:.4f}")
print(f"- Learning Rate (Alpha)    : {alpha}")


print("\nOptimization Progress:")
print(f"- Epoch 20 Loss            : {loss_history[19]:.4f}")
print(f"- Epoch 40 Loss            : {loss_history[39]:.4f}")
print(f"- Epoch 60 Loss            : {loss_history[59]:.4f}")
print(f"- Epoch 80 Loss            : {loss_history[79]:.4f}")
print(f"- Epoch 100 Loss           : {loss_history[99]:.4f}")


print("\nEvaluation Metrics:")
print(f"- Final Training Loss      : {loss_history[-1]:.4f}")
print(f"- Classification Accuracy  : {accuracy * 100:.2f}%")
print("- Decision Threshold       : 0.50")


print("\nEngine Outcome:")
print("Custom Neural Network trained successfully using pure NumPy forward and backward passes.")


========== WEEK 5 DAY 21: NEURAL NETWORK ENGINE FROM SCRATCH ==========

Architecture Parameters:
- Input Features           : 4
- Hidden Layer Neurons     : 8 (Activation: ReLU)
- Output Neurons           : 1 (Activation: Sigmoid)
- Dataset Records          : 50 Samples

Training Initialization:
- Loss Function            : Binary Cross-Entropy (BCE)
- Optimizer                : Vanilla Gradient Descent (SGD)
- Initial Loss (Epoch 1)   : 0.6930
- Learning Rate (Alpha)    : 0.1

Optimization Progress:
- Epoch 20 Loss            : 0.6914
- Epoch 40 Loss            : 0.6841
- Epoch 60 Loss            : 0.6408
- Epoch 80 Loss            : 0.4885
- Epoch 100 Loss           : 0.2884

Evaluation Metrics:
- Final Training Loss      : 0.2884
- Classification Accuracy  : 100.00%
- Decision Threshold       : 0.50

Engine Outcome:
Custom Neural Network trained successfully using pure NumPy forward and backward passes.
